name: StaffManager
version: '1.0-SNAPSHOT'
main: hyperburger.me.staffmanager.StaffManager
api-version: '1.19'
commands:
  staffchat:
    aliases:
      - sc
      - staffc
      - chatstaff
  staffmanager:
    aliases:
      - sm
      - staffm

  report:
    aliases:
      - rep